### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by andreimarinescu**
At least in my case the API call didn't work until I modified the date to be 01-01-2014 (a while after my account creation date)

### CODE REVIEW

**Comment by eek** [comment]
In my case - `2008` as `fromDate` works for accounts made in `2017` as well

**Comment by alentodorov** [comment]
For me it works since 2004 when the account started. One interesting thing tough is that the transactions before denomination can create some confusion = like you'd think you're a millionaire all of a sudden.

**Comment by andreimarinescu** [comment]
Weird. In my case I only got a 300kb file with a few transactions from when the account was created. Once I switched the date to something after that account was created I got the full list. Maybe it has something to do with the account being on a secondary profile that is also for a company account. Closing this in any case, not such a big deal :)

**Comment by eek** [comment]
@alentodorov maybe a fix for that would actually be useful, a map to change all values that have been created before `2005-07-01`

**Pull request closed without merging**
